adis16465_node:
  ros__parameters:
    burst_mode: false
    device: /dev/kuaro/ttyUSBADISIMU
    frame_id: imu_adis
    rate: 200.0
    publish_temperature: false

adis_imu_filter_node:
  ros__parameters:
    constant_dt: 0.0
    declination: 0.0
    fixed_frame: base_link
    gain: 0.1
    mag_bias_x: 0.0
    mag_bias_y: 0.0
    mag_bias_z: 0.0
    orientation_stddev: 0.0
    publish_debug_topics: false
    publish_tf: false
    remove_gravity_vector: false
    reverse_tf: false
    stateless: false
    use_mag: false
    world_frame: enu
    yaw_offset: 0.0
    zeta: 0.0

