lumotive_driver:
  ros__parameters:
    device_frame_id: "m20_lidar"

    # Driver params
    nb_packets_per_frame: 0 # Override for the number of packets per array (0 = automatically computed by driver based on FoV size)
    organized_cloud: true # unorganized pointclouds allow for a smaller payload, organized pointcloud can be processed/converted to images
    color_range_max: 5.0 # color palette range in meters when converting point cloud to depth map
    colormap_name: "turbo" # color palette choice: turbo, inferno, viridis
    color_by_reflectivity: false # point cloud coloring by reflectivity
    range_min: 0.0 # meters, minimum range of a valid detection
    range_max: 12.0 # meters, maximum range of a valid detection
    sensor_ip: "192.168.0.10"
    sensor_port: 10940

    min_brightness: 0.2 # enter a value in range [0., 1.0)
    max_brightness: 10000.0 # this is the maximum value that the reflectivity can take. If this is too high, everything will appear dark
