#
#  Initial Speed Profile
#
whill/ros2_whill:
  ros__parameters:
    serial_port: /dev/kuaro/ttyUSBWhill
    wheel_radius: 0.1325
    # send_interval: 20
    send_interval: 50
    enable_cmd_vel_control: true
    # publish_tf: false
    publish_tf: True
    base_frame_id: whill_link
    odom_frame_id: whill_odom
    imu_frame_id: whill_imu

whill_joy:
  ros__parameters:
    frequency: 10
    pressed_duration: 0.1
    # Sequentially, front(0 ~ 2): speed, acceleration, deceleration / back(3 ~ 5): speed, acceleration, deceleration / turn(6 ~ 8): speed, acceleration, deceleration
    # speed m/s acceleration m/ss deceleration m/ss (Motor)
    
    # fm, fa, fd, rm, ra, rd, tm, ta, td  :config
    # 8   10  40  8   10  40  8   10  40  :min
    # ~   ~   ~   ~   ~   ~   ~   ~   ~
    # 60  90  160 30  50  90  35  60  160 :max
    speed_profile_initial: [
      29, 16, 100, 12, 24, 64, 29, 35, 100
    ]

    # speed mode 0 ~ 3 for Whill Joystick.
    # speed mode 4 is for RS232
    # speed mode 5 is for Phone